import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Signin from "@/components/Signin";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex h-screen w-screen ">
        <div className="flex h-full w-3/5 flex-col">
          <div className="flex items-center justify-between h-20 w-full border-b border-solid border-borderColor p-5">
            <div>
              <h6 className="font-montserrat text-colorText">MSM</h6>
              <p className="font-montserrat text-colorText">
                Menuiserie Sur Mesure
              </p>
            </div>
            <div className="flex flex-row justify-around w-1/2 items-center">
              <p className="font-montserrat font-light text-colorText">
                Vous ne possédez pas de compte ?
              </p>
              <button className="text-colorText font-bold border border-solid border-colorText p-3 rounded-lg hover:shadow-lg">
                Inscription
              </button>
            </div>
          </div>
          <div className="flex items-center justify-center h-4/5 w-full">
            <Signin />
          </div>
        </div>
        <div className="flex items-center justify-center h-full bg-colorBrown w-2/5">
          <div className="flex flex-col h-1/2 w-2/3 items-center justify-center">
            <img
              src="https://static.wixstatic.com/media/d16931_c1db014fc2a04a16a7b140679667eb46~mv2.png/v1/fill/w_96,h_96,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/logo_MSM_w_bg.png"
              alt="logo_MSM_w_bg.png"
              srcset="https://static.wixstatic.com/media/d16931_c1db014fc2a04a16a7b140679667eb46~mv2.png/v1/fill/w_96,h_96,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/logo_MSM_w_bg.png"
            />
            <h1 className="text-5xl font-bold text-white font-montserrat">
              MSM
            </h1>
            <h2 className="text-3xl font-bold text-white font-montserrat">
              Menuiserie Sur Mesure
            </h2>
          </div>
        </div>
      </main>
    </>
  );
}
